org.jitsi.impl.neomedia.transform.dtls.DtlsPacketTransformer.dropUnencryptedPkts=true
org.jitsi.jirecon.JIRECON_NICKNAME=jirecon
org.jitsi.jirecon.MAX_STREAM_PORT=10000
org.jitsi.jirecon.MIN_STREAM_PORT=8000
org.jitsi.jirecon.OUTPUT_DIR=/recordings
org.jitsi.jirecon.XMPP_HOST=xmpp.meet.jitsi
org.jitsi.jirecon.XMPP_PORT=5222
org.jitsi.jirecon.XMPP_USER=recorder@hidden.meet.jitsi
org.jitsi.jirecon.XMPP_PASS=688a7f6f09876560f132631476fb9ba3
